-- Intentionally empty. Schema is owned by Prisma migrations (see prisma/).
-- This file runs once when the Docker Postgres volume is first created;
-- after that, apply schema via `npm run db:migrate`.
