#!/usr/bin/env bash
# Configure a worktree's ports, compose project, and .env.local.
#
# Usage: scripts/setup-worktree.sh <N>
#   N=0 is the main checkout; N≥1 is a .claude/worktrees/wtN checkout.
#
# Derived values per worktree N:
#   VITE_PORT            = 3000 + N   (dev server)
#   POSTGRES_HOST_PORT   = 5434 + N   (docker compose)
#   POSTGRES_VOLUME_NAME = analyst-pgdata[-wtN]
#   COMPOSE_PROJECT_NAME = analyst[-wtN]
#   VITE_WT_LABEL        = ""|WT<N>   (shown in page title + sidebar brand)

set -euo pipefail

N="${1:-}"
if ! [[ "$N" =~ ^[0-9]+$ ]]; then
  echo "Usage: $0 <worktree-number>" >&2
  exit 1
fi

VITE_PORT=$((3000 + N))
POSTGRES_HOST_PORT=$((5434 + N))
if [[ "$N" == "0" ]]; then
  COMPOSE_PROJECT_NAME="analyst"
  POSTGRES_VOLUME_NAME="analyst-pgdata"
  WT_LABEL=""
else
  COMPOSE_PROJECT_NAME="analyst-wt${N}"
  POSTGRES_VOLUME_NAME="analyst-pgdata-wt${N}"
  WT_LABEL="WT${N}"
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
ENV_LOCAL="$REPO_ROOT/.env.local"

# --- .env (read by docker compose) -------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-worktree.sh for worktree ${N}. Do not edit by hand.
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
POSTGRES_VOLUME_NAME=${POSTGRES_VOLUME_NAME}
EOF

# --- .env.local (read by Vite / dotenv-cli) ----------------------------------
touch "$ENV_LOCAL"

update_var() {
  local key="$1"
  local val="$2"
  local tmp
  tmp="$(mktemp)"
  grep -vE "^${key}=" "$ENV_LOCAL" > "$tmp" || true
  if [[ -n "$val" ]]; then
    echo "${key}=${val}" >> "$tmp"
  fi
  mv "$tmp" "$ENV_LOCAL"
}

# For N>=1, inherit per-user secrets from the main worktree's .env.local so
# Clerk / Sentry / Anthropic / etc. don't have to be pasted by hand in every
# worktree. Per-worktree overrides (VITE_PORT, DATABASE_URL, …) below take
# precedence over anything pulled in here.
if [[ "$N" != "0" ]]; then
  MAIN_DIR="$(git -C "$REPO_ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2; exit}')"
  MAIN_ENV="${MAIN_DIR:-}/.env.local"
  if [[ -n "$MAIN_DIR" && -f "$MAIN_ENV" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
      key="${line%%=*}"
      # Don't copy keys that the worktree script owns below.
      case "$key" in
        VITE_PORT|VITE_WT_LABEL|DATABASE_URL) continue ;;
      esac
      if ! grep -qE "^${key}=" "$ENV_LOCAL" 2>/dev/null; then
        printf '%s\n' "$line" >> "$ENV_LOCAL"
      fi
    done < "$MAIN_ENV"
    echo "Inherited secrets from $MAIN_ENV"
  fi
fi

update_var VITE_PORT "$VITE_PORT"
update_var VITE_WT_LABEL "$WT_LABEL"
update_var DATABASE_URL "postgresql://analyst:analyst@localhost:${POSTGRES_HOST_PORT}/analyst"

echo "Configured worktree ${N}:"
echo "  VITE_PORT            = ${VITE_PORT}"
echo "  POSTGRES_HOST_PORT   = ${POSTGRES_HOST_PORT}"
echo "  COMPOSE_PROJECT_NAME = ${COMPOSE_PROJECT_NAME}"
echo "  POSTGRES_VOLUME_NAME = ${POSTGRES_VOLUME_NAME}"
echo "  VITE_WT_LABEL        = ${WT_LABEL:-<none>}"
echo
echo "Next steps:"
echo "  docker compose up -d"
echo "  npm run db:migrate"
echo "  npm run dev    # → http://localhost:${VITE_PORT}/"
