/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiLogsRouteImport } from './routes/api.logs'
import { Route as AdminTickersRouteImport } from './routes/admin/tickers'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminPromptRouteImport } from './routes/admin/prompt'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminFactorsRouteImport } from './routes/admin/factors'
import { Route as AdminExtractorRouteImport } from './routes/admin/extractor'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminPricesIndexRouteImport } from './routes/admin/prices/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram.webhook'
import { Route as ApiTelegramRegisterRouteImport } from './routes/api.telegram.register'
import { Route as ApiCronIngestPricesRouteImport } from './routes/api.cron.ingest-prices'
import { Route as ApiCronIngestNewsRouteImport } from './routes/api.cron.ingest-news'
import { Route as ApiCronExtractRouteImport } from './routes/api.cron.extract'
import { Route as AdminPricesSymbolRouteImport } from './routes/admin/prices/$symbol'
import { Route as AdminEventsSlugRouteImport } from './routes/admin/events/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTickersRoute = AdminTickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromptRoute = AdminPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFactorsRoute = AdminFactorsRouteImport.update({
  id: '/factors',
  path: '/factors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtractorRoute = AdminExtractorRouteImport.update({
  id: '/extractor',
  path: '/extractor',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPricesIndexRoute = AdminPricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRegisterRoute = ApiTelegramRegisterRouteImport.update({
  id: '/api/telegram/register',
  path: '/api/telegram/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIngestPricesRoute = ApiCronIngestPricesRouteImport.update({
  id: '/api/cron/ingest-prices',
  path: '/api/cron/ingest-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIngestNewsRoute = ApiCronIngestNewsRouteImport.update({
  id: '/api/cron/ingest-news',
  path: '/api/cron/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExtractRoute = ApiCronExtractRouteImport.update({
  id: '/api/cron/extract',
  path: '/api/cron/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricesSymbolRoute = AdminPricesSymbolRouteImport.update({
  id: '/prices/$symbol',
  path: '/prices/$symbol',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsSlugRoute = AdminEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
  '/admin/prices/$symbol': typeof AdminPricesSymbolRoute
  '/api/cron/extract': typeof ApiCronExtractRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/cron/ingest-prices': typeof ApiCronIngestPricesRoute
  '/api/telegram/register': typeof ApiTelegramRegisterRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/prices/': typeof AdminPricesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
  '/admin/prices/$symbol': typeof AdminPricesSymbolRoute
  '/api/cron/extract': typeof ApiCronExtractRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/cron/ingest-prices': typeof ApiCronIngestPricesRoute
  '/api/telegram/register': typeof ApiTelegramRegisterRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/prices': typeof AdminPricesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/extractor': typeof AdminExtractorRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
  '/admin/prices/$symbol': typeof AdminPricesSymbolRoute
  '/api/cron/extract': typeof ApiCronExtractRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/cron/ingest-prices': typeof ApiCronIngestPricesRoute
  '/api/telegram/register': typeof ApiTelegramRegisterRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/prices/': typeof AdminPricesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/prompt'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin/'
    | '/admin/events/$slug'
    | '/admin/prices/$symbol'
    | '/api/cron/extract'
    | '/api/cron/ingest-news'
    | '/api/cron/ingest-prices'
    | '/api/telegram/register'
    | '/api/telegram/webhook'
    | '/api/trpc/$'
    | '/admin/events/'
    | '/admin/prices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/prompt'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin'
    | '/admin/events/$slug'
    | '/admin/prices/$symbol'
    | '/api/cron/extract'
    | '/api/cron/ingest-news'
    | '/api/cron/ingest-prices'
    | '/api/telegram/register'
    | '/api/telegram/webhook'
    | '/api/trpc/$'
    | '/admin/events'
    | '/admin/prices'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/admin/candidates'
    | '/admin/extractor'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/prompt'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin/'
    | '/admin/events/$slug'
    | '/admin/prices/$symbol'
    | '/api/cron/extract'
    | '/api/cron/ingest-news'
    | '/api/cron/ingest-prices'
    | '/api/telegram/register'
    | '/api/telegram/webhook'
    | '/api/trpc/$'
    | '/admin/events/'
    | '/admin/prices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiCronExtractRoute: typeof ApiCronExtractRoute
  ApiCronIngestNewsRoute: typeof ApiCronIngestNewsRoute
  ApiCronIngestPricesRoute: typeof ApiCronIngestPricesRoute
  ApiTelegramRegisterRoute: typeof ApiTelegramRegisterRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickers': {
      id: '/admin/tickers'
      path: '/tickers'
      fullPath: '/admin/tickers'
      preLoaderRoute: typeof AdminTickersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prompt': {
      id: '/admin/prompt'
      path: '/prompt'
      fullPath: '/admin/prompt'
      preLoaderRoute: typeof AdminPromptRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/factors': {
      id: '/admin/factors'
      path: '/factors'
      fullPath: '/admin/factors'
      preLoaderRoute: typeof AdminFactorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extractor': {
      id: '/admin/extractor'
      path: '/extractor'
      fullPath: '/admin/extractor'
      preLoaderRoute: typeof AdminExtractorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prices/': {
      id: '/admin/prices/'
      path: '/prices'
      fullPath: '/admin/prices/'
      preLoaderRoute: typeof AdminPricesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/register': {
      id: '/api/telegram/register'
      path: '/api/telegram/register'
      fullPath: '/api/telegram/register'
      preLoaderRoute: typeof ApiTelegramRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ingest-prices': {
      id: '/api/cron/ingest-prices'
      path: '/api/cron/ingest-prices'
      fullPath: '/api/cron/ingest-prices'
      preLoaderRoute: typeof ApiCronIngestPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ingest-news': {
      id: '/api/cron/ingest-news'
      path: '/api/cron/ingest-news'
      fullPath: '/api/cron/ingest-news'
      preLoaderRoute: typeof ApiCronIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/extract': {
      id: '/api/cron/extract'
      path: '/api/cron/extract'
      fullPath: '/api/cron/extract'
      preLoaderRoute: typeof ApiCronExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prices/$symbol': {
      id: '/admin/prices/$symbol'
      path: '/prices/$symbol'
      fullPath: '/admin/prices/$symbol'
      preLoaderRoute: typeof AdminPricesSymbolRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$slug': {
      id: '/admin/events/$slug'
      path: '/events/$slug'
      fullPath: '/admin/events/$slug'
      preLoaderRoute: typeof AdminEventsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminExtractorRoute: typeof AdminExtractorRoute
  AdminFactorsRoute: typeof AdminFactorsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPromptRoute: typeof AdminPromptRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTickersRoute: typeof AdminTickersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsSlugRoute: typeof AdminEventsSlugRoute
  AdminPricesSymbolRoute: typeof AdminPricesSymbolRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminPricesIndexRoute: typeof AdminPricesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminExtractorRoute: AdminExtractorRoute,
  AdminFactorsRoute: AdminFactorsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPromptRoute: AdminPromptRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTickersRoute: AdminTickersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsSlugRoute: AdminEventsSlugRoute,
  AdminPricesSymbolRoute: AdminPricesSymbolRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminPricesIndexRoute: AdminPricesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiCronExtractRoute: ApiCronExtractRoute,
  ApiCronIngestNewsRoute: ApiCronIngestNewsRoute,
  ApiCronIngestPricesRoute: ApiCronIngestPricesRoute,
  ApiTelegramRegisterRoute: ApiTelegramRegisterRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
