/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiLogsRouteImport } from './routes/api.logs'
import { Route as AdminTickersRouteImport } from './routes/admin/tickers'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminFactorsRouteImport } from './routes/admin/factors'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiCronIngestNewsRouteImport } from './routes/api.cron.ingest-news'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTickersRoute = AdminTickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFactorsRoute = AdminFactorsRouteImport.update({
  id: '/factors',
  path: '/factors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIngestNewsRoute = ApiCronIngestNewsRouteImport.update({
  id: '/api/cron/ingest-news',
  path: '/api/cron/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/factors': typeof AdminFactorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/tickers': typeof AdminTickersRoute
  '/api/logs': typeof ApiLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/ingest-news': typeof ApiCronIngestNewsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin/'
    | '/api/cron/ingest-news'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin'
    | '/api/cron/ingest-news'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/admin/factors'
    | '/admin/news'
    | '/admin/sources'
    | '/admin/tickers'
    | '/api/logs'
    | '/admin/'
    | '/api/cron/ingest-news'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiCronIngestNewsRoute: typeof ApiCronIngestNewsRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickers': {
      id: '/admin/tickers'
      path: '/tickers'
      fullPath: '/admin/tickers'
      preLoaderRoute: typeof AdminTickersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/factors': {
      id: '/admin/factors'
      path: '/factors'
      fullPath: '/admin/factors'
      preLoaderRoute: typeof AdminFactorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ingest-news': {
      id: '/api/cron/ingest-news'
      path: '/api/cron/ingest-news'
      fullPath: '/api/cron/ingest-news'
      preLoaderRoute: typeof ApiCronIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFactorsRoute: typeof AdminFactorsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTickersRoute: typeof AdminTickersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFactorsRoute: AdminFactorsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTickersRoute: AdminTickersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiCronIngestNewsRoute: ApiCronIngestNewsRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
